In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ventas.csv")

In [4]:
df

       Vendedor      Producto  Cantidad  Precio       Fecha
0    Ana Torres  Curso Python         3  $29.99  2026-01-05
1   Carlos Rios      Curso IA         1  $49.99  2026-01-07
2   Maria Lopez  Curso Python         2  $29.99  2026-01-08
3    Ana Torres      Curso ML         1  $39.99  2026-01-10
4   Pedro Salas  Curso Python         4  $29.99  2026-01-12
5   Carlos Rios  Curso Python         2  $29.99  2026-01-15
6   Maria Lopez      Curso IA         1  $49.99  2026-01-18
7   Pedro Salas      Curso ML         2  $39.99  2026-01-20
8    Ana Torres      Curso IA         2  $49.99  2026-01-22
9   Carlos Rios      Curso ML         3  $39.99  2026-01-25
10  Maria Lopez  Curso Python         1  $29.99  2026-01-28
11  Pedro Salas      Curso IA         1  $49.99  2026-02-01
12   Ana Torres  Curso Python         2  $29.99  2026-02-03
13  Carlos Rios  Curso Python         3  $29.99  2026-02-06
14  Maria Lopez      Curso ML         2  $39.99  2026-02-08
15  Pedro Salas  Curso Python         1  $29.99  2026-02-10
16   Ana Torres      Curso ML         3  $39.99  2026-02-12
17  Carlos Rios      Curso IA         2  $49.99  2026-02-15
18  Maria Lopez  Curso Python         4  $29.99  2026-02-18
19  Pedro Salas      Curso ML         1  $39.99  2026-02-20
20   Ana Torres      Curso IA         1  $49.99  2026-02-22
21  Carlos Rios  Curso Python         2  $29.99  2026-02-25
22  Maria Lopez      Curso IA         3  $49.99  2026-02-28
23  Pedro Salas  Curso Python         2  $29.99  2026-03-02
24   Ana Torres  Curso Python         1  $29.99  2026-03-05
25  Carlos Rios      Curso ML         1  $39.99  2026-03-07
26  Maria Lopez      Curso ML         3  $39.99  2026-03-10
27  Pedro Salas      Curso IA         2  $49.99  2026-03-12
28   Ana Torres      Curso ML         2  $39.99  2026-03-15
29  Carlos Rios      Curso IA         1  $49.99  2026-03-18

In [5]:
df.head()

      Vendedor      Producto  Cantidad  Precio       Fecha
0   Ana Torres  Curso Python         3  $29.99  2026-01-05
1  Carlos Rios      Curso IA         1  $49.99  2026-01-07
2  Maria Lopez  Curso Python         2  $29.99  2026-01-08
3   Ana Torres      Curso ML         1  $39.99  2026-01-10
4  Pedro Salas  Curso Python         4  $29.99  2026-01-12

In [7]:
df["Precio"]

0     $29.99
1     $49.99
2     $29.99
3     $39.99
4     $29.99
5     $29.99
6     $49.99
7     $39.99
8     $49.99
9     $39.99
10    $29.99
11    $49.99
12    $29.99
13    $29.99
14    $39.99
15    $29.99
16    $39.99
17    $49.99
18    $29.99
19    $39.99
20    $49.99
21    $29.99
22    $49.99
23    $29.99
24    $29.99
25    $39.99
26    $39.99
27    $49.99
28    $39.99
29    $49.99
Name: Precio, dtype: str

In [9]:
df["Precio"] = df["Precio"].str.replace("$", "", regex=False)

In [10]:
df["Precio"] = df["Precio"].astype(float)

In [11]:
df["Precio"].sum()

np.float64(1169.7)